name: 04 - Using Actions
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 04-using-actions/react-app 
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install tree
              run: sudo apt-get install tree
            - name: Printing folders
              run:  tree

