name: 05 - 2 - Event filters and activity types
on:
    pull_request:
        types: [closed]
        branches:
            - main
jobs: 
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Print message
              run: echo "Running whenever a pr is closed"
